CREATE TABLE IF NOT EXISTS Trips (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    UNIQUE KEY (name)
);

CREATE TABLE IF NOT EXISTS Pics (
    id INT PRIMARY KEY AUTO_INCREMENT,
    trip_id INT NOT NULL,
    datetime DATETIME NOT NULL,
    location POINT NOT NULL,
    image_url VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    FOREIGN KEY (trip_id) REFERENCES Trips (id) ON DELETE CASCADE ON UPDATE CASCADE,
    SPATIAL INDEX (location)
);

CREATE TABLE IF NOT EXISTS Tags (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    UNIQUE KEY (name)
);

CREATE TABLE IF NOT EXISTS PicsTags (
    pic_id INT NOT NULL,
    tag_id INT NOT NULL,
    FOREIGN KEY (pic_id) REFERENCES Pics (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES Tags (id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (pic_id, tag_id)
);

CREATE TABLE IF NOT EXISTS Regions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    located_in_id INT,
    native_language_name VARCHAR(100) NOT NULL,
    korean_name VARCHAR(100) NOT NULL,
    geometry MULTIPOLYGON NOT NULL,
    geojson TEXT NOT NULL,
    FOREIGN KEY (located_in_id) REFERENCES Regions (id) ON DELETE CASCADE ON UPDATE CASCADE,
    SPATIAL INDEX (geometry)
);
